Junk = {}

JunkTable = {
  "ARM_Gloves_Hide",
  "ARR_Arrow_Normal",
  "BASE_CONS_Drink_Potion",
  "BASE_LOOT_Arrow",
  "BASE_LOOT_Belt",
  "BASE_LOOT_Dye",
  "BASE_LOOT_Gem",
  "BASE_LOOT_Music",
  "BASE_LOOT_Necklace",
  "BGO_Cabbage_Spoiled",
  "CINE_ARR_Arrow_Normal",
  "CINE_CONS_GEN_Drink_Mug_Metal_A_Empty",
  "CINE_DEC_Dungeon_Skeleton_Skull_A",
  "CINE_DEC_FARM_Bucket_A",
  "CINE_DEC_GEN_Ink_Pot_Quill_A",
  "CINE_DEC_GEN_KitchenInstrument_Spoon_B_Wood_A",
  "CINE_DEC_GEN_Paintbrush_A",
  "CINE_LOOT_Alchemy_Crystal_I",
  "CINE_LOOT_GEN_Needle_A",
  "CINE_LOOT_GEN_Palette_Paint_A",
  "CINE_LOOT_GEN_Poop_A",
  "CINE_LOOT_GEN_Poop_B",
  "CINE_LOOT_GEN_Wheat_A",
  "CINE_LOOT_GOB_Spear_Tip_A",
  "CINE_TOOL_Camp_Bedroll_Open_A",
  "CINE_TOOL_Camp_Bedroll_Open_C",
  "CINE_TOOL_GEN_Broom_B",
  "CINE_TOOL_GEN_Hammer_Repair_A",
  "CINE_TOOL_GEN_Tong_A",
  "CINE_TOOL_GOB_Branding_Tool_A",
  "CINE_TOOL_GTY_Microscope_A",
  "CINE_TOOL_Masonry_Hammer_A",
  "CONS_Drink_Bottle_Small_A",
  "CONS_Drink_Bottle_Small_B",
  "CONS_Drink_Bottle_Small_C",
  "CONS_Drink_Bottle_Small_D",
  "CONS_Drink_Bottle_Small_E",
  "CONS_Drink_Potion_A",
  "CONS_Drink_Potion_B",
  "CONS_Drink_Potion_C",
  "CONS_Drink_Potion_D",
  "CONS_Drink_Wine_Glass_A",
  "CONS_FOOD_Fish_Rotten_A",
  "CONS_FOOD_Fish_Rotten_B",
  "CONS_FOOD_Fish_Rotten_C",
  "CONS_FOOD_Fish_Rotten_D",
  "CONS_FOOD_Fruit_Banana_A_Rotten",
  "CONS_FOOD_Fruit_Lemon_A_Rotten",
  "CONS_FOOD_Mushroom_Bluecap",
  "CONS_FOOD_Vegetable_Carrot_A_Rotten",
  "CONS_FOOD_Vegetable_Tomato_A_Rotten",
  "CONS_Fungi_Mushroom_Agaric_A_Rotten",
  "CONS_Fungi_Mushroom_Agaric_B_Rotten",
  "CONS_GEN_Alcohol_Bottle_Cheap_D",
  "CONS_GEN_Drink_Cup_Metal_A_Empty",
  "CONS_GEN_Drink_Cup_Metal_A_Flipped",
  "CONS_GEN_Drink_Cup_Metal_A_Oil",
  "CONS_GEN_Drink_Mug_Metal_A_Beer",
  "CONS_GEN_Drink_Mug_Metal_A_Empty",
  "CONS_GEN_Food_Cheese_Blue_Piece_A_Rotten",
  "CONS_GEN_Food_Cheese_Blue_Piece_B_Rotten",
  "CONS_GEN_Food_Cheese_Blue_Wheel_A_Rotten",
  "CONS_GEN_Food_Cheese_Cheddar_Piece_A_Rotten",
  "CONS_GEN_Food_Cheese_Cheddar_Piece_B_Rotten",
  "CONS_GEN_Food_Cheese_Cheddar_Wheel_A_Rotten",
  "CONS_GEN_Food_Cheese_Goat_Piece_A_Rotten",
  "CONS_GEN_Food_Cheese_Goat_Piece_B_Rotten",
  "CONS_GEN_Food_Cheese_Goat_Wheel_A_Rotten",
  "CONS_GEN_Food_Eggs_A_Rotten",
  "CONS_GEN_Food_Plate_A",
  "CONS_GEN_Food_Plate_B",
  "CONS_GEN_Rotten_Food",
  "CONT_Jergal_Urn_Bones_A",
  "DEC_Dungeon_Skeleton_Skull_A_Bloody_A",
  "DEC_Dungeon_Skeleton_Skull_A",
  "DEC_GEN_Gore_Pile_A_DarkUrgeButler",
  "DEC_GEN_Gore_Pile_A",
  "DEC_GEN_Hanging_Furnace_Pot_A",
  "DEC_GEN_Ink_Pot_Closed_A",
  "DEC_GEN_Ink_Pot_Open_A",
  "DEC_GEN_Ink_Pot_Quill_A",
  "DEC_GEN_Ink_Pot_QuillAndPot_A",
  "DEC_GEN_Junk_A_FishSkeleton_A",
  "DEC_GEN_Kitchen_Bucket_A",
  "DEC_GEN_Kitchen_Cutlery_Glass_Poor_A",
  "DEC_GEN_Kitchen_Cutlery_Plate_Poor_A",
  "DEC_GEN_Kitchen_CuttingBoard_A",
  "DEC_GEN_Kitchen_Pan_A",
  "DEC_GEN_Kitchen_Pan_B",
  "DEC_GEN_Kitchen_Plate_A",
  "DEC_GEN_Kitchen_Pot_A",
  "DEC_GEN_Kitchen_Pot_B",
  "DEC_GEN_Kitchen_Pot_C",
  "DEC_GEN_Owlbear_Plush_Toy_A",
  "DEC_GEN_Towel_A",
  "DEC_GEN_Towel_B",
  "DEC_GEN_Towel_Blood_Holding_A",
  "DEC_GEN_Towel_Bloody_A",
  "DEC_GEN_Towel_Bloody_B",
  "DEC_GEN_Towel_Bloody_C",
  "DEC_GEN_Towel_C",
  "DEC_GEN_Towels_Pile_A",
  "DEC_GEN_Towels_Pile_B",
  "DEC_GEN_Towels_Pile_Bloody_A",
  "DEC_GEN_Towels_Pile_Bloody_B",
  "DEC_GEN_Towels_Stacked_A_converted",
  "DEC_GEN_Towels_Stacked_A",
  "DEC_GEN_Towels_Stacked_B_converted",
  "DEC_GEN_Towels_Stacked_B",
  "DEC_GEN_Towels_Stacked_Bloody_A",
  "DEC_GEN_Towels_Stacked_Bloody_B",
  "DEC_GEN_Towels_Stacked_Bloody_C",
  "DEC_GEN_Towels_Stacked_Bloody_D",
  "DEC_GEN_Towels_Stacked_Bloody_E",
  "DEC_GEN_Towels_Stacked_Bloody_F",
  "DEC_GEN_Towels_Stacked_C_converted",
  "DEC_GEN_Towels_Stacked_C",
  "DEC_GEN_Towels_Stacked_D_converted",
  "DEC_GEN_Towels_Stacked_D",
  "DEC_GEN_Towels_Stacked_E_converted",
  "DEC_GEN_Towels_Stacked_E",
  "DEC_GEN_Towels_Stacked_F_converted",
  "DEC_GEN_Towels_Stacked_F",
  "DEC_HAG_Tea_Pot_A",
  "DEC_HAG_Totem_Props_Bottle_A",
  "DEC_HAG_Totem_Props_Bowl_A",
  "DEC_HAR_Bucket_Empty_A",
  "DEC_HAR_FishingRod_A",
  "DEC_HAR_FishingRod_B",
  "DEC_HAR_FishingRod_C",
  "DEC_HAR_Pier_Rope_A",
  "DEC_Harbour_Shell_Conch_B",
  "DEC_Harbour_Shell_Conch_C",
  "DEC_Harbour_Shell_Starfish_A",
  "DEC_Harbour_Shell_Venus_A",
  "DEC_Hospital_Bloodbank_Transfusion_Bottle_B",
  "DEC_Laboratory_Flask_Glass_Installation_A_GlowA",
  "DEC_Laboratory_Flask_Glass_Installation_A",
  "DEC_Laboratory_Flask_Glass_Installation_B_Empty_A",
  "DEC_Laboratory_Flask_Glass_Installation_B_GlowA",
  "DEC_Laboratory_Flask_Glass_Installation_B",
  "DEC_Laboratory_Flask_Glass_Installation_C_Empty_A",
  "DEC_Laboratory_Flask_Glass_Installation_C_GlowA",
  "DEC_Laboratory_Flask_Glass_Installation_C",
  "DEC_Laboratory_Flask_Glass_Installation_D_Empty_A",
  "DEC_Laboratory_Flask_Glass_Installation_D_Glow_Green_A",
  "DEC_Laboratory_Flask_Glass_Installation_D_GlowA",
  "DEC_Laboratory_Flask_Glass_Installation_D",
  "DEC_Laboratory_Flask_Glass_Installation_E_Empty_A",
  "DEC_Laboratory_Flask_Glass_Installation_E_GlowA",
  "DEC_Laboratory_Flask_Glass_Installation_E",
  "FUR_GEN_Kitchen_Cup_Glass_A",
  "FUR_GEN_Kitchen_Cup_Glass_B",
  "LAB_GEN_Bottle_A",
  "LAB_GEN_Bottle_B",
  "LAB_GEN_Bottle_C",
  "LAB_GEN_Bottle_D",
  "LAB_GEN_Bottle_E",
  "LOOT_Dungeon_SharTemple_Gem_A",
  "LOOT_Dungeon_Skeleton_Animal_RamBone_A",
  "LOOT_Dungeon_Skeleton_Animal_RamBone_B",
  "LOOT_GEN_Bedlinen_A_Folded",
  "LOOT_GEN_Bowl_Metal_A",
  "LOOT_GEN_Bowl_Wooden_A_Frog_A",
  "LOOT_GEN_Bowl_Wooden_A",
  "LOOT_GEN_Charcoal_A",
  "LOOT_GEN_Charcoal_B",
  "LOOT_GEN_Charcoal_C",
  "LOOT_GEN_Charcoal_D",
  "LOOT_GEN_Charcoal_E",
  "LOOT_GEN_DryBone_A",
  "LOOT_GEN_Ghastly_Bottles_A",
  "LOOT_GEN_Ghastly_Bottles_B",
  "LOOT_GEN_Ghastly_Bottles_C",
  "LOOT_GEN_Ghastly_Bottles_D",
  "LOOT_GEN_Ghastly_Bottles_E",
  "LOOT_GEN_Ghastly_Bottles_F",
  "LOOT_GEN_Ghastly_Bottles_G",
  "LOOT_GEN_Junk_A_FishSkeleton_A",
  "LOOT_GEN_Toy_TeddyBear_A_Clean",
  "LOOT_GEN_Toy_TeddyBear_A_Worn",
  "LOOT_GEN_Toy_TeddyBear_B",
  "LOOT_GEN_Toy_TeddyBear_C",
  "LOOT_GEN_Toy_TeddyBear_D",
  "LOOT_GEN_Toy_TeddyBear_E",
  "LOOT_GEN_Toy_TeddyBear_F",
  "LOOT_GEN_Toy_TeddyBear_G",
  "LOOT_GEN_Toy_WoodenBlock_A",
  "LOOT_GEN_Toy_WoodenBlock_B",
  "LOOT_GEN_Toy_WoodenBlock_C",
  "LOOT_GEN_Toy_WoodenBlock_D",
  "LOOT_GEN_Wheat_A",
  "LOOT_GOB_Spear_Tip_A",
  "LOOT_HAG_Skeleton_Ribs_A",
  "LOOT_Smith_Bellows_A",
  "LOOT_Smith_Tongs_A",
  "LOOT_Smith_Tongs_B",
  "LOOT_Smith_Tongs_C",
  "LOOT_Smith_Tongs_D",
  "LOOT_Smith_Tongs_E",
  "TOOL_Camp_Bedroll_Closed_A",
  "TOOL_Camp_Bedroll_Open_A",
  "TOOL_Camp_Bedroll_Open_B",
  "TOOL_Camp_Bedroll_Open_C",
  "TOOL_Camp_Bedroll_Open_D",
  "TOOL_Camp_Bedroll_Open_E",
  "TOOL_Camp_Bedroll_Open_F",
  "TOOL_Camp_Bedroll_Open_G",
  "TOOL_Camp_Bedroll_Open_H",
  "TOOL_GEN_Broom_A",
  "TOOL_GEN_Broom_B",
  "TOOL_GEN_Hammer_Repair_A",
  "TOOL_GEN_Identifying_Glass_A",
  "TOOL_GEN_Pitchfork_A",
  "TOOL_GEN_Tong_A",
  "TOOL_GOB_Branding_Tool_A",
  "TOOL_GTY_Microscope_A",
  "TOOL_Hospital_Surgery_Kit_A",
  "TOOL_Hospital_Surgery_Kit_B",
  "TOOL_Masonry_Chisel_Kit_A",
  "TOOL_Masonry_Hammer_A",
  "TOOL_Rope_A",
}


function Junk.SaveTableAsJSONIfNotExists(defaultTable, filePath)
  if not Config.JSONFileExists(filePath) then
    local jsonString = defaultTable
    Config.SaveConfig(filePath, jsonString)
    Utils.DebugPrint(0, "Ignored items JSON file created: " .. filePath)
  else
    Utils.DebugPrint(1, "Ignored items JSON file already exists: " .. filePath)
  end
end

Junk.SaveTableAsJSONIfNotExists(JunkTable, "ignored_items.json")

-- REFACTOR: make the JSON have the item names as keys instead of a list
function Junk.LoadIgnoredItems()
  local ignoredItemsList = Config.LoadConfig("ignored_items.json")
  if ignoredItemsList then
    Utils.DebugPrint(0, "Loaded ignored items JSON file: ignored_items.json")
    -- Convert the list into a table with item names as keys for easier lookup
    local ignoredItemsTable = {}
    for _, itemName in ipairs(ignoredItemsList) do
      ignoredItemsTable[itemName] = true
    end
    return ignoredItemsTable
  else
    Utils.DebugPrint(1, "Ignored items JSON file not found: ignored_items.json")
    return {}
  end
end

IgnoredItems = Junk.LoadIgnoredItems()
Utils.DebugPrint(1, "Loaded " .. tostring(#IgnoredItems) .. " ignored items")

return Junk
